# Generated by Django 6.0.3 on 2026-03-14 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('maintainer', 'Maintainer'), ('reader', 'Reader')], max_length=20)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='repositories.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('repository_id', 'user_id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'repository'), name='uniq_user_repo_role')],
            },
        ),
    ]
