# Generated by Django 6.0.3 on 2026-03-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('type', models.CharField(choices=[('deb', 'Debian APT'), ('rpm', 'RPM'), ('pypi', 'PyPI'), ('msi', 'MSI'), ('generic', 'Generic')], max_length=20)),
                ('mode', models.CharField(choices=[('local', 'Local'), ('remote', 'Remote'), ('virtual', 'Virtual')], default='local', max_length=20)),
                ('remote_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
