# Generated by Django 6.0.3 on 2026-03-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryTypePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_deb', models.BooleanField(default=True)),
                ('allow_rpm', models.BooleanField(default=True)),
                ('allow_pypi', models.BooleanField(default=True)),
                ('allow_msi', models.BooleanField(default=True)),
                ('allow_generic', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repository type policy',
                'verbose_name_plural': 'Repository type policies',
            },
        ),
    ]
